# Generated by Django 3.1.3 on 2021-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0011_auto_20210405_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(related_name='content', to='Timeline.Postfiles'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='Timeline.Tag'),
        ),
    ]
