# Generated by Django 3.1.3 on 2021-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0054_auto_20210501_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(related_name='content', to='Timeline.Postfiles'),
        ),
    ]
