# Generated by Django 3.1.3 on 2021-05-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0055_auto_20210502_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_liked',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(related_name='content', to='Timeline.Postfiles'),
        ),
    ]
