# Generated by Django 3.1.3 on 2021-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timeline', '0004_auto_20210402_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='post_id',
            field=models.ManyToManyField(related_name='post', to='Timeline.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.ManyToManyField(related_name='content', to='Timeline.Postfiles'),
        ),
    ]
