# Generated by Django 3.1.3 on 2021-04-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Directors',
        ),
    ]
